############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Benefits"
url = ""
weight = 2

[[main]]
name = "Channels"
url = ""
weight = 3

[[main]]
name = "Security"
url = ""
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5


# Footer menu
[[footer]]
name = "Home"
url = ""
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 6