############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Benefits"
url = "#b2b-excellence-made-simple"
weight = 2

[[main]]
name = "Channels"
url = "#available-in-online-and-offline-channels"
weight = 3

[[main]]
name = "Security"
url = "#malas-robust-security"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5


# Footer menu
[[footer]]
name = "Home"
url = ""
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 6